[package]
name = "twelve-days"
version = "0.1.0"
authors = ["jwnpoh <jwn.poh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uint = "0.9.0"
